name: build_bundle

on:
  push:
    branches:
      - 'play'
    workflow_dispatch:

jobs:
  BuildBundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build sing-box library
        run: |
          make build

      - name: Set local properties
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          touch local.properties
          echo KEYSTORE_PASS="$SIGNING_STORE_PASSWORD" >> local.properties
          echo ALIAS_NAME="$SIGNING_KEY_ALIAS" >> local.properties
          echo ALIAS_PASS="$SIGNING_KEY_PASSWORD" >> local.properties

      - name: Release Build
        if: success()
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon app:bundleRelease

      - name: Release file asset
        run: |
          cd app/build/outputs/bundle/release
          echo "ASSET_NAME=$(ls *.aab)" >> $GITHUB_ENV
          cd -

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ASSET_NAME }}
          path: |
            app/build/outputs/bundle/release/*.aab
